swagger: "2.0"
info:
  version: 1.0.0
  title: backend
  description: My cool app
basePath: /api
tag: 
- name: "auth"
  description: "Everything about sign up and sign in"
schemes:
- "https"
- "http"
paths:
  /auth/register:
    post:
      tags:
      - "auth"
      summary:
      - "Register new account"
      description: ""
      produces: 
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object that needs to be added to the user db"
        required: true
        schema: 
        $ref: "#/definitions/newAccount"
      responses:
        200:
          description: "Register success"
        405:
          description: "Invalid input"
definitions:
  type: "object"
  required:
  - "role_id"
  - "first_name"
  - "last_name"
  - "email"
  - "phone_num"
  properties:
    role_id:
      type: "integer"
      enum: 
      - 1
      - 2
    first_name:
      type: "string"
      example: "thao"
    last_name:
      type: "string"
      example: "nguyen"
    email:
      type: "string"
      example: "thaonp041099@gmail.com"
    phone_num:
      type: "string"
      example: "0912345566"
 
       

  


consumes:
  - application/json
produces:
  - application/json


# definitions:
#   ExampleBody:
#     type: object
#     title: example
#     required:
#       - name
#     properties:
#       name:
#         type: string
#         example: no_stress

# paths:
#   /examples:
#     get:
#       tags:
#         - Examples
#       description: Fetch all examples
#       responses:
#         200:
#           description: Returns all examples
#     post:
#       tags:
#         - Examples
#       description: Create a new example
#       parameters:
#         - name: example
#           in: body
#           description: an example
#           required: true
#           schema: 
#             $ref: "#/definitions/ExampleBody"
#       responses:
#         200:
#           description: Returns all examples

#   /examples/{id}:
#     get:
#       tags:
#         - Examples
#       parameters:
#         - name: id
#           in: path
#           required: true
#           description: The id of the example to retrieve
#           type: integer
#       responses:
#         200:
#           description: Return the example with the specified id
#         404:
#           description: Example not found

#   /spec:
#     get:
#       tags:
#         - Specification
#       responses:
#         200:
#           description: Return the API specification

  paths:
    /auth/login:
      post:
        tag:
          - Login
        parameters
        description: user login
        parameter:
          - name: email
            in: body
            require: true
            description: email of user
            type: String
          - name: password
            in: body
            require: true
            description: user password
            type: String
        respond:
          - 200: 
              description: go to user's page
          - 401:
              description: email or password incorrect
        
