swagger: "2.0"
info:
  version: 1.0.0
  title: backend
  description: My cool app
basePath: /api
tag: 
- name: "auth"
  description: "Everything about sign up and sign in"

consumes:
  - application/json
produces:
  - application/json

# definitions:

definitions:
  loginInfo:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
      password:
        type: string
  newAccount:
    type: object
    required:
    - role
    - first_name
    - last_name
    - email
    - phone_num
    - password
    - gender_name
    properties:
      role:
        type: string
      first_name:
        type: string
      last_name:
          type: string
      email:
        type: string
      phone_num:
        type: string
      password:
        type: string
      gender_name:
        type: string

paths:
  /user/register:
    post:
      tags:
        - user
      description: Register new account
      parameters:
       - name: info
         in: body
         require: true
         description: User object that needs to be added to the user db
         schema: 
           $ref: "#/definitions/newAccount"
      respond:
        - 200:
          description: Register success
        - 405:
          description: Invalid input

  /auth/login:
    post:
      tags:
        - Login
      description: user login
      parameters:
        - account:
          in: body
          require: true
          description: user account
          schema: 
            $ref: "#/definitions/loginInfo"
      respond:
        - 200: 
            description: go to user's page
        - 401:
            description: email or password incorrect
        

 
       


# definitions:
#   ExampleBody:
#     type: object
#     title: example
#     required:
#       - name
#     properties:
#       name:
#         type: string
#         example: no_stress

# paths:
#   /examples:
#     get:
#       tags:
#         - Examples
#       description: Fetch all examples
#       responses:
#         200:
#           description: Returns all examples
#     post:
#       tags:
#         - Examples
#       description: Create a new example
#       parameters:
#         - name: example
#           in: body
#           description: an example
#           required: true
#           schema: 
#             $ref: "#/definitions/ExampleBody"
#       responses:
#         200:
#           description: Returns all examples

#   /examples/{id}:
#     get:
#       tags:
#         - Examples
#       parameters:
#         - name: id
#           in: path
#           required: true
#           description: The id of the example to retrieve
#           type: integer
#       responses:
#         200:
#           description: Return the example with the specified id
#         404:
#           description: Example not found

#   /spec:
#     get:
#       tags:
#         - Specification
#       responses:
#         200:
#           description: Return the API specification
