# swagger: "2.0"
# info:
#   version: 1.0.0
#   title: backend
#   description: My cool app
# basePath: /api

# tags:
#   - name: Examples
#     description: Simple example endpoints
# - name: Specification
#     description: The swagger API specification

# consumes:
#   - application/json
# produces:
#   - application/json


# # definitions:
# #   ExampleBody:
# #     type: object
# #     title: example
# #     required:
# #       - name
# #     properties:
# #       name:
# #         type: string
# #         example: no_stress

# paths:
#   /examples:
#     get:
#       tags:
#         - Examples
#       description: Fetch all examples
#       responses:
#         200:
#           description: Returns all examples
#     post:
#       tags:
#         - Examples
#       description: Create a new example
#       parameters:
#         - name: example
#           in: body
#           description: an example
#           required: true
#           schema: 
#             $ref: "#/definitions/ExampleBody"
#       responses:
#         200:
#           description: Returns all examples

#   /examples/{id}:
#     get:
#       tags:
#         - Examples
#       parameters:
#         - name: id
#           in: path
#           required: true
#           description: The id of the example to retrieve
#           type: integer
#       responses:
#         200:
#           description: Return the example with the specified id
#         404:
#           description: Example not found

#   /spec:
#     get:
#       tags:
#         - Specification
#       responses:
#         200:
#           description: Return the API specification

swagger: "2.0"
info:
  version: 1.0.0
  title: backend
  description: My cool app
basePath: /api

definitions:
    Users:
      type: object
      title: user
      required:
        - account
        - role
        - profile
      propperties:
        account:
          type: object
          required:
            - email
            - password
          propertuies:
            email:
              -type: string
            password:
              -type: string
        role:
          type: string
        profile:
          type: object
          required:
            - firstname
            - lastname
            - nationality
            - gender_name
            - race_name
            - identity_number
            - dob
            - language_name
            - academic_level_name
          properties:
            first_name:
              type: string
            last_name:
              type: string
            phone_code:
              type: number
            phone_number:
              type: number
            payment_method:
              type: string
            bank_name:
              type: string
            account_number:
              type: number
            paypal_email:
              type: string
            other_name:
              type: string
            country_name:
              type: string
            nationality_name:
              type: string
            race_name:
              type: string
            gender_name:
              type: string
            religion_name:
              type: string
            academic_level_name_name:
              type: string
            language_name:
              type: string
            city_name:
              type: string
            date_of_birth:
              type: date
            no_passport:
              type: number
            address:
              type: string
            postal_code:
              type: number
            country:
              type: string
            profile_picture:
              type: buffer
            language_user:
              type: string
    Tutors:
      type: object
      required:
        - user_id
        - reference
        - working_experience
        - teaching subject
        - calender
      properties:
        user_id:
          type: string
          reference:
            type: object
            required:
              - about_me
              - major
              -profile_picture
              - institute
              - certificate
            properties:
              about_me:
                type: string
              profile_picture:
                type: buffer
              major:
                type: string
              institute:
                type: string
              certificate:
                type: array
        reference:
          type: object
          required:
            - year
            - experience
          propperties:
            year:
              type: number
            experience:
              type: array
        teaching_subject:
          type: object
          required:
            -fee_per_hour
            -fee_commitions
            -fee_earn
            -note
            -user
            -country
            -academic_level
            -academic_grade
            -course
          properties:
            fee_per_hour:
              type: number
            fee_commitions:
              type: number
            fee_earn:
              type: number
            note:
              type: string
            country:
              type: string
            academic_level:
              type: string
            academic_grade:
              type: string 
            course:
              type: array
        calendar:
          type: object
          require:
            - start_date
            - end_date
            - status
          properties:
            - start_date:
              type: date
            - end_date:
              type: date
            - status:
              type: string

















# tags:
#   - name: Specification
#     description: The swagger API specification

# definitions:
#     User:
#       type: object
#       title: user
#       required:
#         - account
#         - role
#         - profile
#         - schedule
#       propperties:
#         account:
#           type: object
#           required:
#             - email
#             - password
#           propertuies:
#             email:
#               -type: string
#             password:
#               -type: string
#         role:
#           type: object
#           required:
#             - tutor
#             - student
#           propperties:
#             tutor:
#               type: object
#               required:
#                 - schedule
#                 - detail
#               properties:
#                 schedule:
#                   type: object
#                   require:
#                     - start_time
#                     - end_time
#                 tutor_detail:
#         profile:
#           type: object
#           required:
#             - firstname
#             - lastname
#             - nationality
#             - gender_name
#             - race_name
#             - identity_number
#             - dob
#             - language_name
#             - academic_level_name
#           properties:
#             first_name:
#               type: string
#             last_name:
#               type: string
#             phone_code:
#               type: number
#             phone_number:
#               type: number
#             payment_method:
#               type: string
#             bank_name:
#               type: string
#             account_number:
#               type: number
#             paypal_email:
#               type: string
#             other_name:
#               type: string
#             country_name:
#               type: string
#             nationality_name:
#               type: string
#             race_name:
#               type: string
#             gender_name:
#               type: string
#             religion_name:
#               type: string
#             academic_level_name_name:
#               type: string
#             language_name:
#               type: string
#             city_name:
#               type: string
#             date_of_birth:
#               type: date
#             no_passport:
#               type: number
#             address:
#               type: string
#             postal_code:
#               type: number
#             country:
#               type: string
#             profile_picture:
#               type: buffer
#             language_user:
#               type: string
#         schedule:

